/// Flutter icons BodyIcon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BodyIcon
///      fonts:
///       - asset: fonts/BodyIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BodyIcon {
  BodyIcon._();

  static const _kFontFam = 'BodyIcon';
  static const String? _kFontPkg = null;

  static const IconData forehead = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nose = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ear_icon = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData see_icon = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tongue_icon = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
