/// Flutter icons HBXapp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HBXapp
///      fonts:
///       - asset: fonts/HBXapp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class HBXapp {
  HBXapp._();

  static const _kFontFam = 'HBXapp';
  static const _kFontPkg = null;

  static const IconData user = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back_ico = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_ico = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cross_ico = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete_ico = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document_ico = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download_ico = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_ico = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_icon = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_hide_ico = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_show_ico = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tick_ico_1 = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData funnel_ico = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back_arrow = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gray_bell_ico_2 = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_ico = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData next_arrow = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData no_doc_ico = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gray_bell_ico_1 = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification_icon = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_ico = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData save_ico = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_ico = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share_ico = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tick_ico = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
